### ISSUE TITLE
Improve the README.md

### ISSUE THREAD

**Issue by luiskjr** [MSFS-Mega-Pack/MSFS2020-livery-manager#44]
How does it start ?
What the f*** means "yarn start" in the README.md ??????

Couldnt you guys be a little more specific?

**Comment by luiskjr** [comment]
Where is the "Electron app" ? there is no such thing!

You should only make reference to files in your directory. There is a yarn.lock (that does nothing)
There is NO yarn start o electron app

**Comment by davwheat** [comment]
yarn is a package manager, like npm...

We use yarn instead of npm because it is much faster to download and link dependencies.

yarn start is a script inside `package.json`

https://github.com/MSFS-Mega-Pack/MSFS2020-livery-manager/blob/da7d95e1c8d80c0d221ae2ca88e4c048e36087f9/package.json#L18

![image](https://user-images.githubusercontent.com/7406822/93022129-45748e00-f5df-11ea-9e1d-fdc960925b46.png)
